# Generated by Django 5.1.1 on 2024-11-19 22:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0004_order_discount_applied'),
        ('profiles', '0002_userprofile_full_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='LoyaltyPointsTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_type', models.CharField(choices=[('EARN', 'Points Earned'), ('REDEEM', 'Points Redeemed')], max_length=10)),
                ('points', models.IntegerField()),
                ('balance_before', models.IntegerField()),
                ('balance_after', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='checkout.order')),
                ('user_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='points_transactions', to='profiles.userprofile')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
