# Generated by Django 5.1.1 on 2024-12-20 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0012_alter_contactmessage_user_alter_repairrequest_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='usermessage',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
