# Generated by Django 5.1.1 on 2024-12-23 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0013_usermessage_updated_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactmessage',
            name='has_response',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='contactmessage',
            name='responded_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='orderissue',
            name='has_response',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='orderissue',
            name='responded_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='repairrequest',
            name='has_response',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='repairrequest',
            name='responded_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
