# Generated by Django 5.1.1 on 2024-12-23 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0014_contactmessage_has_response_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='usermessage',
            name='is_new_response',
            field=models.BooleanField(default=False),
        ),
    ]
