# Generated by Django 5.1.1 on 2024-12-23 10:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0015_usermessage_is_new_response'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usermessage',
            name='is_new_response',
        ),
    ]
