# Generated by Django 5.1.1 on 2024-11-16 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0002_alter_orderlineitem_lineitem_total'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='loyalty_points_used',
            field=models.IntegerField(default=0),
        ),
    ]
