# Generated by Django 5.1.1 on 2024-11-18 20:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0003_order_loyalty_points_used'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='discount_applied',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True),
        ),
    ]
