# Generated by Django 5.1.1 on 2024-09-27 11:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=254)),
                ('friendly_name', models.CharField(blank=True, max_length=254, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sku', models.CharField(blank=True, max_length=254, null=True)),
                ('name', models.CharField(max_length=254)),
                ('description', models.TextField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('rating', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='')),
                ('color', models.CharField(blank=True, max_length=50, null=True)),
                ('rotors', models.IntegerField(blank=True, null=True)),
                ('speed', models.CharField(blank=True, max_length=50, null=True)),
                ('weight', models.CharField(blank=True, max_length=50, null=True)),
                ('flight_time', models.CharField(blank=True, max_length=50, null=True)),
                ('camera', models.CharField(blank=True, max_length=10, null=True)),
                ('camera_quality', models.CharField(blank=True, max_length=100, null=True)),
                ('collision_avoidance', models.CharField(blank=True, max_length=10, null=True)),
                ('gps', models.CharField(blank=True, max_length=10, null=True)),
                ('control_range', models.CharField(blank=True, max_length=50, null=True)),
                ('max_altitude', models.CharField(blank=True, max_length=50, null=True)),
                ('wind_resistance', models.CharField(blank=True, max_length=50, null=True)),
                ('material', models.CharField(blank=True, max_length=100, null=True)),
                ('remote_control', models.CharField(blank=True, max_length=10, null=True)),
                ('mobile_app_support', models.CharField(blank=True, max_length=50, null=True)),
                ('warranty', models.CharField(blank=True, max_length=50, null=True)),
                ('compatibility', models.CharField(blank=True, max_length=254, null=True)),
                ('package_contents', models.TextField(blank=True, null=True)),
                ('drones_included', models.IntegerField(blank=True, null=True)),
                ('drone_model', models.CharField(blank=True, max_length=254, null=True)),
                ('accessories_included', models.TextField(blank=True, null=True)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='products.category')),
            ],
        ),
    ]
