# Generated by Django 5.1.1 on 2024-12-22 05:55

import custom_storages
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_alter_productreview_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, null=True, storage=custom_storages.MediaStorage(), upload_to=''),
        ),
    ]
